### ISSUE TITLE
cutout2D feature request

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaAstro/WCS.jl#36]
The 2D cutout feature from astropy was a really useful wrapper that it would be great to implement. 

https://docs.astropy.org/en/stable/nddata/utils.html

**Comment by mileslucas** [comment]
What particularly about `Cutout2D` is significant with WCS?

We can natively cut out segments from an `AbstractArray` with `view`. The code for calculating indices from a center and size exists in `PSFModels.jl`, for example. For shifting the indices we can use `OffsetArray`. I'm just not certain where this method would actually belong, since it's just an indexing trick.

**Comment by andrew-saydjari** [comment]
So, I was under the impression that Cutout2D correctly maintained the rotation matrix/information in the FITS header. A cursory glance at the astropy source suggests that it does not. So I will amend the feature request to be an implementation of this nice indexing trick/wrapper and correct implementation of passing all information including the image rotation onto the new FITS header.
